### ISSUE TITLE
Add option to scan all realms

### ISSUE THREAD

**Issue by ptarjan** [italankin/wow-auction-notify-bot#4]
Now that warbands allow gold to move easily across realms, can you add a way to scan ALL realms? Especially for the MARKET_PRICE auctions. This would make it easier to find pets or mounts you are missing for much cheaper on a random other realm.

**Comment by italankin** [comment]
Thanks for your interest in the project.

But, unfortunately, I’m not playing WoW anymore, so I don’t think I’ll be adding any new features anytime soon.

**Comment by ptarjan** [comment]
Thanks for the transparency. After getting your project to work I found https://github.com/ff14-advanced-market-search/mega-alerts which does handle pets and all realms (the two requests I had for your project) so I'm using that now.
