### ISSUE TITLE
Handle pets

### ISSUE THREAD

**Issue by ptarjan** [italankin/wow-auction-notify-bot#5]
Pets are weird in the API. It looks like all auctions for them come out as id `82800` https://www.wowhead.com/item=82800/pet-cage and have the actual pet in `pet_species_id` which, of course, isn't related at all to the BoP item that is found when you search for the pet name in the item API. Here is an example:

```
2024-09-24 15:27:35,669 - wow.wow_game_api - INFO - auction['item']={'id': 82800, 'modifiers': [{'type': 6, 'value': 95172}], 'pet_breed_id': 13, 'pet_level': 25, 'pet_quality_id': 3, 'pet_species_id': 2843}
```

Hopefully there is some way to map the BoP item to the `pet_species_id`.

**Comment by italankin** [comment]
https://github.com/italankin/wow-auction-notify-bot/issues/4#issuecomment-2379848815
